version: 1.0.{build}
image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python 3.8.0\\python.exe"
    - PYTHON: "C:\\Study\\Pythonprojects\\testingapp"
    - PYTHON: "C:\\Study\\PyCharm\\bin\\pycharm64.exe"

install:
  - ps: Install-Product node $env:APPVEYOR_BUILD_WORKER_IMAGE_VERSION
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install -r requirements.txt

build_script:
  - python setup.py build

test_script:
  - python setup.py test

deploy_script:
  - python setup.py sdist bdist_wheel
  - pip install twine
  - twine upload dist/*
