version: 1.0.{build}
image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Install-Package Python -Version $env:PYTHON

build_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py build

test_script:
  - pytest

deploy_script:
  - pip install twine
  - twine upload dist/*