version: 1.0.{build}
configuration: Release
before_build:
- nuget restore
build:
verbocity: minimal
publish_wap: true
environment:
  matrix:
    - PYTHON: "C:\\Study\\Python 3.8.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Install-Package Python -Version $env:PYTHON

build_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py build

test_script:
  - pytest

deploy_script:
  - pip install twine
  - twine upload dist/*
